name: Update CSV and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update_sw_eventlist.py
        env:
          DOORKEEPER_API_KEY: ${{ secrets.DOORKEEPER_API_KEY }}
        run: python update_sw_eventlist.py

      - name: Commit updated files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add startup_weekend_events.csv last_run_time.txt
          git commit -m 'Update CSV and timestamp'
          git push

      - name: Clean up files
        run: |
          mkdir public
          mv index.html public/
          mv startup_weekend_events.csv public/
          mv last_run_time.txt public/
          mv streamlit_app.py public/

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
